name: Big Bang Evolution
favicon: null
layout_spectrum: 0
typography_spectrum: 0.1538
title: Big Bang Evolution
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-41248496-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d1114'
    - '#ad432d'
    - '#747474'
    - '#a7a7a7'
  brandStrength: 0.4375
  lightness: 0.331986581441015
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
