name: Big bang evolution
favicon: null
layout_spectrum: 0.5584776357281953
typography_spectrum: 0.9961959789507091
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4497461123391986
  lightness: 0.331986581441015
  saturation: 0.4959612232632935
  rhythmicContrast: 0.7042421321384609
purpose: []
