name: Big Bang Evolution
favicon: null
layout_spectrum: 0.50872
typography_spectrum: 0.58328
title: Big Bang Evolution
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-41248496-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d1114'
    - '#ad432d'
    - '#747474'
    - '#a7a7a7'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
